version: 2

run:
  timeout: 5m
  go: "1.22"

linters:
  enable:
    - revive
    - govet
    - staticcheck
    - gosec
    - errcheck
    - exhaustive
    - unused

issues:
  # Show all issues, not just the first few per linter.
  max-issues-per-linter: 0
  max-same-issues: 0
